export const TOOLBAR_OPTIONS = [
  [{ header: [1, 2, 3, 4, 5, 6, false] }],
  ["bold", "italic", "underline", "strike"],
  [{ list: "ordered" }, { list: "bullet" }, { indent: "-1" }, { indent: "+1" }],
  [{ color: ["red", "green", "blue", "violet"] }],
  [{ script: "sub" }, { script: "super" }],
  [{ align: ["", "center", "right"] }],
  ["link", "image", "code-block", "blockquote"],
  ["clean"],
];

export const formats = [
  "header",
  "font",
  "bold",
  "italic",
  "underline",
  "align",
  "strike",
  "script",
  "list",
  "bullet",
  "indent",
  "link",
  "image",
  "video",
  "color",
  "code-block",
  "blockquote",
];
